# Generated by Django 5.2.7 on 2025-10-24 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lockers", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="locker",
            options={
                "ordering": ["locker_number"],
                "verbose_name": "Locker",
                "verbose_name_plural": "Lockers",
            },
        ),
    ]
